<?php

namespace Database\Factories;

use App\Models\Collection;
use App\Models\User;
use Illuminate\Database\Eloquent\Factories\Factory;

class CollectionFactory extends Factory
{
    protected $model = Collection::class;

    public function definition()
    {
        return [
            'name' => $this->faker->randomElement([
                'Action Games',
                'Adventure Games',
                'Role-Playing Games',
                'Simulation Games',
                'Strategy Games',
                'Sports Games',
                'Puzzle Games',
                'Idle Games',
                'Shooter Games',
                'Fighting Games',
                'Stealth Games',
                'Survival Games',
                'Horror Games',
                'Platform Games',
                'Racing Games',
                'Rhythm Games',
                'Sandbox Games',
                'Open World Games',
                'MMORPGs',
                'MOBA Games',
                'Battle Royale Games',
                'Card Games',
                'Board Games',
                'Trivia Games',
                'Educational Games',
                'Party Games',
                'Music Games',
                'Dance Games',
                'Fitness Games',
                'VR Games',
                'AR Games',
                'Mobile Games',
                'PC Games',
                'Console Games',
                'Handheld Games',
                'Retro Games',
                'Indie Games',
                'AAA Games',
                'Multiplayer Games',
                'Single Player Games',
                'Co-op Games',
                'Competitive Games',
                'Casual Games',
                'Hardcore Games',
                'Story-Driven Games',
                'Non-Linear Games',
                'Puzzle Platformers',
                'Metroidvania Games',
                'Roguelike Games',
                'Roguelite Games',
                'Soulslike Games',
                'Deckbuilding Games',
                'Tower Defense Games',
                'Turn-Based Strategy Games',
                'Real-Time Strategy Games',
                '4X Games',
                'Grand Strategy Games',
                'City-Building Games',
                'Management Games',
                'Tycoon Games',
                'Life Simulation Games',
                'Dating Simulation Games',
                'Visual Novels',
                'Interactive Fiction',
                'Text-Based Games',
                'Point-and-Click Games',
                'Hidden Object Games',
                'Escape Room Games',
                'Match-3 Games',
                'Tile-Matching Games',
                'Physics-Based Games',
                'Endless Runner Games',
                'Bullet Hell Games',
                'Shoot \'em Up Games',
                'Beat \'em Up Games',
                'Hack and Slash Games',
                'Dungeon Crawlers',
                'Looters',
                'Crafting Games',
                'Building Games',
                'Farming Games',
                'Fishing Games',
                'Hunting Games',
                'Cooking Games',
                'Baking Games',
                'Gardening Games',
                'Pet Simulation Games',
                'Monster Taming Games',
                'Creature Collecting Games',
                'Breeding Games',
                'Raising Games',
                'Training Games',
                'Sports Management Games',
                'Team Management Games',
                'Player Management Games',
                'Franchise Management Games',
                'League Management Games',
                'Tournament Management Games',
                'Event Management Games',
                'Simulation Racing Games',
                'Arcade Racing Games',
                'Kart Racing Games',
                'Combat Racing Games',
                'Vehicular Combat Games',
                'Flight Simulation Games',
                'Space Simulation Games',
                'Submarine Simulation Games',
                'Train Simulation Games',
                'Truck Simulation Games',
                'Bus Simulation Games',
                'Ship Simulation Games',
                'Boat Simulation Games',
                'Yacht Simulation Games',
                'Sailing Simulation Games',
                'Fishing Simulation Games',
                'Hunting Simulation Games',
                'Survival Horror Games',
                'Psychological Horror Games',
                'Gothic Horror Games',
                'Lovecraftian Horror Games',
                'Zombie Games',
                'Vampire Games',
                'Werewolf Games',
                'Ghost Games',
                'Demon Games',
                'Monster Games',
                'Alien Games',
                'Sci-Fi Games',
                'Fantasy Games',
                'Medieval Games',
                'Historical Games',
                'Western Games',
                'Steampunk Games',
                'Cyberpunk Games',
                'Post-Apocalyptic Games',
                'Dystopian Games',
                'Utopian Games',
                'Mythology Games',
                'Folklore Games',
                'Fairy Tale Games',
                'Superhero Games',
                'Villain Games',
                'Detective Games',
                'Mystery Games',
                'Crime Games',
                'Heist Games',
                'Spy Games',
                'Espionage Games',
                'Military Games',
                'War Games',
                'Naval Games',
                'Air Combat Games',
                'Space Combat Games',
                'Mecha Games',
                'Robot Games',
                'Alien Invasion Games',
                'Time Travel Games',
                'Dimension Hopping Games',
                'Parallel Universe Games',
                'Alternate History Games',
                'Historical Fiction Games',
                'Science Fiction Games',
                'Fantasy Fiction Games',
                'Horror Fiction Games',
                'Romance Fiction Games',
                'Comedy Games',
                'Satire Games',
                'Parody Games',
                'Dark Comedy Games',
                'Political Games',
                'Economic Games',
                'Social Games',
                'Cultural Games',
                'Religious Games',
                'Philosophical Games',
                'Educational Games',
                'Training Games',
                'Skill-Building Games',
                'Brain Training Games',
                'Memory Games',
                'Logic Games',
                'Math Games',
                'Language Games',
                'Science Games',
                'History Games',
                'Geography Games',
                'Art Games',
                'Music Games',
                'Dance Games',
                'Fitness Games',
                'Health Games',
                'Wellness Games',
                'Meditation Games',
                'Yoga Games',
                'Mindfulness Games',
                'Relaxation Games',
                'Stress Relief Games',
                'Therapy Games',
                'Rehabilitation Games',
                'Accessibility Games',
                'Inclusive Games',
                'Diverse Games',
                'Representation Games',
                'LGBTQ+ Games',
                'Gender Games',
                'Race Games',
                'Ethnicity Games',
                'Culture Games',
                'Religion Games',
                'Philosophy Games',
                'Politics Games',
                'Economics Games',
                'Society Games',
                'Community Games',
                'Family Games',
                'Friends Games',
                'Relationship Games',
                'Dating Games',
                'Marriage Games',
                'Parenting Games',
                'Childcare Games',
                'Elder Care Games',
                'Pet Care Games',
                'Animal Care Games',
                'Wildlife Games',
                'Nature Games',
                'Environmental Games',
                'Conservation Games',
                'Sustainability Games',
                'Green Games',
                'Eco-Friendly Games',
                'Climate Change Games',
                'Global Warming Games',
                'Pollution Games',
                'Recycling Games',
                'Waste Management Games',
                'Energy Games',
                'Renewable Energy Games',
                'Solar Energy Games',
                'Wind Energy Games',
                'Hydro Energy Games',
                'Geothermal Energy Games',
                'Nuclear Energy Games',
                'Fossil Fuel Games',
                'Oil Games',
                'Gas Games',
                'Coal Games',
                'Mining Games',
                'Resource Management Games',
                'Supply Chain Games',
                'Logistics Games',
                'Transportation Games',
                'Shipping Games',
                'Delivery Games',
                'Courier Games',
                'Postal Games',
                'Mail Games',
                'Package Games',
                'Parcel Games',
                'Freight Games',
                'Cargo Games',
                'Warehouse Games',
                'Inventory Games',
                'Stock Management Games',
                'Retail Games',
                'E-Commerce Games',
                'Online Shopping Games',
                'Marketplace Games',
                'Auction Games',
                'Bidding Games',
                'Trading Games',
                'Investment Games',
                'Stock Market Games',
                'Finance Games',
                'Banking Games',
                'Insurance Games',
                'Real Estate Games',
                'Property Management Games',
                'Landlord Games',
                'Tenant Games',
                'Rental Games',
                'Lease Games',
                'Mortgage Games',
                'Loan Games',
                'Credit Games',
                'Debt Games',
                'Savings Games',
                'Budgeting Games',
                'Expense Management Games',
                'Income Management Games',
                'Tax Games',
                'Accounting Games',
                'Bookkeeping Games',
                'Payroll Games',
                'HR Games',
                'Recruitment Games',
                'Job Search Games',
                'Career Games',
                'Professional Development Games',
                'Skill Development Games',
                'Training Games',
                'Certification Games',
                'Licensing Games',
                'Compliance Games',
                'Regulation Games',
                'Policy Games',
                'Governance Games',
                'Leadership Games',
                'Management Games',
                'Strategy Games',
                'Tactics Games',
                'Operations Games',
                'Project Management Games',
                'Program Management Games',
                'Portfolio Management Games',
                'Risk Management Games',
                'Crisis Management Games',
                'Disaster Management Games',
                'Emergency Management Games',
                'Safety Games',
                'Security Games',
                'Defense Games',
                'Protection Games',
                'Surveillance Games',
                'Monitoring Games',
                'Detection Games',
                'Investigation Games',
                'Forensics Games',
                'Crime Scene Games',
                'Evidence Games',
                'Witness Games',
                'Testimony Games',
                'Trial Games',
                'Courtroom Games',
                'Legal Games',
                'Law Games',
                'Justice Games',
                'Rights Games',
                'Liberty Games',
                'Freedom Games',
                'Equality Games',
                'Equity Games',
                'Fairness Games',
                'Inclusion Games',
                'Diversity Games',
                'Representation Games',
                'Advocacy Games',
                'Activism Games',
                'Campaign Games',
                'Movement Games',
                'Protest Games',
                'Demonstration Games',
                'Rally Games',
                'March Games',
                'Strike Games',
                'Boycott Games',
                'Petition Games',
                'Lobbying Games',
                'Negotiation Games',
                'Mediation Games',
                'Arbitration Games',
                'Conflict Resolution Games',
                'Peace Games',
                'Harmony Games',
                'Unity Games',
                'Solidarity Games',
                'Cooperation Games',
                'Collaboration Games',
                'Partnership Games',
                'Alliance Games',
                'Coalition Games',
                'Network Games',
                'Community Games',
                'Society Games',
                'Culture Games',
                'Tradition Games',
                'Heritage Games',
                'History Games',
                'Archaeology Games',
                'Anthropology Games',
                'Sociology Games',
                'Psychology Games',
                'Philosophy Games',
                'Religion Games',
                'Spirituality Games',
                'Mysticism Games',
                'Occult Games',
                'Magic Games',
                'Witchcraft Games',
                'Wizardry Games',
                'Alchemy Games',
                'Sorcery Games',
                'Enchantment Games',
                'Spellcasting Games',
                'Potion Making Games',
                'Herbology Games',
                'Astrology Games',
                'Astronomy Games',
                'Space Exploration Games',
                'Planetary Games',
                'Galactic Games',
                'Universe Games',
                'Multiverse Games',
                'Dimension Games',
                'Parallel Universe Games',
                'Alternate Reality Games',
                'Virtual Reality Games',
                'Augmented Reality Games',
                'Mixed Reality Games',
                'Extended Reality Games',
                'Immersive Games',
                'Interactive Games',
                'Engaging Games',
                'Fun Games',
                'Entertaining Games',
                'Enjoyable Games',
                'Exciting Games',
                'Thrilling Games',
                'Adventurous Games',
                'Challenging Games',
                'Difficult Games',
                'Hard Games',
                'Easy Games',
                'Simple Games',
                'Complex Games',
                'Intricate Games',
                'Detailed Games',
                'Rich Games',
                'Deep Games',
                'Meaningful Games',
                'Impactful Games',
                'Influential Games',
                'Inspirational Games',
                'Motivational Games',
                'Encouraging Games',
                'Empowering Games',
                'Uplifting Games',
                'Positive Games',
                'Optimistic Games',
                'Hopeful Games',
                'Joyful Games',
                'Happy Games',
                'Cheerful Games',
                'Bright Games',
                'Colorful Games',
                'Vibrant Games',
                'Lively Games',
                'Dynamic Games',
                'Energetic Games',
                'Active Games',
                'Busy Games',
                'Fast-Paced Games',
                'Slow-Paced Games',
                'Relaxing Games',
                'Calm Games',
                'Peaceful Games',
                'Serene Games',
                'Tranquil Games',
                'Quiet Games',
                'Silent Games',
                'Noisy Games',
                'Loud Games',
                'Boisterous Games',
                'Rowdy Games',
                'Wild Games',
                'Crazy Games',
                'Insane Games',
                'Mad Games',
                'Frenzied Games',
                'Hectic Games',
                'Chaotic Games',
                'Orderly Games',
                'Organized Games',
                'Structured Games',
                'Systematic Games',
                'Methodical Games',
                'Logical Games',
                'Rational Games',
                'Reasonable Games',
                'Sensible Games',
                'Practical Games',
                'Functional Games',
                'Useful Games',
                'Helpful Games',
                'Beneficial Games',
                'Advantageous Games',
                'Profitable Games',
                'Lucrative Games',
                'Rewarding Games',
                'Fulfilling Games',
                'Satisfying Games',
                'Gratifying Games',
                'Pleasing Games',
                'Delightful Games',
                'Enjoyable Games',
                'Pleasurable Games',
                'Amusing Games',
                'Entertaining Games',
                'Engaging Games',
                'Captivating Games',
                'Fascinating Games',
                'Intriguing Games',
                'Interesting Games',
                'Thought-Provoking Games',
                'Mind-Bending Games',
                'Brain-Teasing Games',
                'Puzzle Games',
                'Riddle Games',
                'Mystery Games',
                'Detective Games',
                'Investigation Games',
                'Crime Games',
                'Thriller Games',
                'Suspense Games',
                'Horror Games',
                'Scary Games',
                'Frightening Games',
                'Terrifying Games',
                'Spooky Games',
                'Creepy Games',
                'Eerie Games',
                'Unsettling Games',
                'Disturbing Games',
                'Haunting Games',
                'Chilling Games',
                'Bone-Chilling Games',
                'Hair-Raising Games',
                'Goosebump-Inducing Games',
                'Nightmare Games',
                'Dream Games',
                'Fantasy Games',
                'Imagination Games',
                'Creativity Games',
                'Art Games',
                'Design Games',
                'Craft Games',
                'DIY Games',
                'Maker Games',
                'Builder Games',
                'Construction Games',
                'Engineering Games',
                'Technology Games',
                'Innovation Games',
                'Invention Games',
                'Discovery Games',
                'Exploration Games',
                'Adventure Games',
                'Journey Games',
                'Quest Games',
                'Expedition Games',
                'Voyage Games',
                'Travel Games',
                'Tourism Games',
                'Vacation Games',
                'Holiday Games',
                'Leisure Games',
                'Recreation Games',
                'Relaxation Games',
                'Wellness Games',
                'Health Games',
                'Fitness Games',
                'Exercise Games',
                'Workout Games',
                'Training Games',
                'Skill-Building Games',
                'Education Games',
                'Learning Games',
                'Knowledge Games',
                'Wisdom Games',
                'Insight Games',
                'Understanding Games',
                'Comprehension Games',
                'Awareness Games',
                'Perception Games',
                'Observation Games',
                'Analysis Games',
                'Evaluation Games',
                'Assessment Games',
                'Judgment Games',
                'Decision-Making Games',
                'Problem-Solving Games',
                'Critical Thinking Games',
                'Logical Reasoning Games',
                'Strategic Thinking Games',
                'Tactical Thinking Games',
                'Operational Thinking Games',
                'Creative Thinking Games',
                'Innovative Thinking Games',
                'Imaginative Thinking Games',
                'Visionary Thinking Games',
                'Futuristic Thinking Games',
                'Forward-Thinking Games',
                'Progressive Thinking Games',
                'Advanced Thinking Games',
                'Cutting-Edge Thinking Games',
                'State-of-the-Art Thinking Games',
                'Leading-Edge Thinking Games',
                'Pioneering Thinking Games',
                'Trailblazing Thinking Games',
                'Groundbreaking Thinking Games',
                'Revolutionary Thinking Games',
                'Transformative Thinking Games',
                'Disruptive Thinking Games',
                'Game-Changing Thinking Games',
                'Paradigm-Shifting Thinking Games',
                'Mind-Blowing Thinking Games',
                'Mind-Expanding Thinking Games',
                'Mind-Opening Thinking Games',
                'Mind-Broadening Thinking Games',
                'Mind-Enhancing Thinking Games',
                'Mind-Improving Thinking Games',
                'Mind-Developing Thinking Games',
                'Mind-Growing Thinking Games',
                'Mind-Evolving Thinking Games',
                'Mind-Progressing Thinking Games',
                'Mind-Advancing Thinking Games',
                'Mind-Forwarding Thinking Games',
                'Mind-Leading Thinking Games',
                'Mind-Pioneering Thinking Games',
                'Mind-Trailblazing Thinking Games',
                'Mind-Groundbreaking Thinking Games',
                'Mind-Revolutionary Thinking Games',
                'Mind-Transformative Thinking Games',
                'Mind-Disruptive Thinking Games'
            ]),
            'description' => $this->faker->sentence,
            'user_id' => User::factory(),
        ];
    }
}
