<?php

namespace Database\Factories;

use App\Models\Game;
use Illuminate\Database\Eloquent\Factories\Factory;

class GameFactory extends Factory
{
    protected $model = Game::class;

    public function definition()
    {
        return [
            'title' => $this->faker->unique()->randomElement([
                'The Legend of Zelda: Breath of the Wild',
                'Super Mario Odyssey',
                'Red Dead Redemption 2',
                'The Witcher 3: Wild Hunt',
                'God of War',
                'Horizon Zero Dawn',
                'Spider-Man',
                'Cyberpunk 2077',
                'Final Fantasy VII Remake',
                'Ghost of Tsushima',
                'Assassin\'s Creed Valhalla',
                'Call of Duty: Modern Warfare',
                'Fortnite',
                'Minecraft',
                'Apex Legends',
                'Overwatch',
                'League of Legends',
                'Valorant',
                'Genshin Impact',
                'Among Us',
                'Animal Crossing: New Horizons',
                'Doom Eternal',
                'Resident Evil Village',
                'Far Cry 6',
                'Battlefield 2042',
                'Halo Infinite',
                'Elden Ring',
                'Death Stranding',
                'Sekiro: Shadows Die Twice',
                'Control',
                'Cyberpunk 2077',
                'The Last of Us Part II',
                'Ghost of Tsushima',
                'Final Fantasy VII Remake',
                'Demon\'s Souls',
                'Ratchet & Clank: Rift Apart',
                'Returnal',
                'Hitman 3',
                'It Takes Two',
                'Hades',
                'Persona 5 Royal',
                'Nioh 2',
                'Yakuza: Like a Dragon',
                'Marvel\'s Avengers',
                'Watch Dogs: Legion',
                'Immortals Fenyx Rising',
                'Mortal Kombat 11',
                'FIFA 21',
                'NBA 2K21',
                'Madden NFL 21',
                'Tony Hawk\'s Pro Skater 1 + 2',
                'Crash Bandicoot 4: It\'s About Time',
                'Spyro Reignited Trilogy',
                'Sonic Mania',
                'Cuphead',
                'Ori and the Will of the Wisps',
                'Hollow Knight',
                'Celeste',
                'Dead Cells',
                'Slay the Spire',
                'Stardew Valley',
                'Terraria',
                'Subnautica',
                'No Man\'s Sky',
                'The Outer Worlds',
                'The Elder Scrolls V: Skyrim',
                'Fallout 4',
                'Mass Effect: Andromeda',
                'Dragon Age: Inquisition',
                'Divinity: Original Sin 2',
                'Pillars of Eternity II: Deadfire',
                'Baldur\'s Gate 3',
                'Disco Elysium',
                'The Banner Saga',
                'XCOM 2',
                'Civilization VI',
                'Total War: Three Kingdoms',
                'Age of Empires II: Definitive Edition',
                'Starcraft II',
                'Warcraft III: Reforged',
                'Diablo III',
                'Path of Exile',
                'Torchlight II',
                'Grim Dawn',
                'Borderlands 3',
                'Destiny 2',
                'Warframe',
                'Anthem',
                'The Division 2',
                'Tom Clancy\'s Ghost Recon Breakpoint',
                'Rainbow Six Siege',
                'For Honor',
                'Chivalry 2',
                'Mordhau',
                'Mount & Blade II: Bannerlord',
                'Kingdom Come: Deliverance',
                'The Witcher 3: Wild Hunt',
                'The Elder Scrolls Online',
                'Final Fantasy XIV',
                'World of Warcraft',
                'Guild Wars 2',
                'Black Desert Online',
                'Star Wars: The Old Republic',
                'EVE Online',
                'Elite Dangerous',
                'Star Citizen',
                'Kerbal Space Program',
                'Factorio',
                'Satisfactory',
                'Cities: Skylines',
                'Planet Coaster',
                'Planet Zoo',
                'Jurassic World Evolution',
                'RollerCoaster Tycoon Classic',
                'SimCity 4',
                'The Sims 4',
                'Two Point Hospital',
                'Theme Hospital',
                'Prison Architect',
                'RimWorld',
                'Oxygen Not Included',
                'Frostpunk',
                'Surviving Mars',
                'Banished',
                'Anno 1800',
                'Tropico 6',
                'Endless Legend',
                'Endless Space 2',
                'Stellaris',
                'Galactic Civilizations III',
                'Sid Meier\'s Pirates!',
                'Port Royale 4',
                'Anno 1404',
                'Patrician IV',
                'Rise of Nations',
                'Empire Earth',
                'Age of Mythology',
                'Stronghold Crusader',
                'Total War: Shogun 2',
                'Total War: Rome II',
                'Total War: Warhammer II',
                'Total War: Attila',
                'Total War: Medieval II',
                'Total War: Napoleon',
                'Total War: Empire',
                'Total War: Three Kingdoms',
                'Total War: Warhammer',
                'Total War: Rome',
                'Total War: Shogun',
                'Total War: Medieval',
                'Total War: Electric Boogaloo',
                'Total War: The Reckoning',
                'Total War: The Return of the King',
                'Total War: The Fellowship of the Ring',
                'Total War: The Two Towers',
                'Total War: The Return of the Jedi',
                'Total War: The Empire Strikes Back',
                'Total War: A New Hope',
                'Total War: The Phantom Menace',
                'Total War: Attack of the Clones',
                'Total War: Revenge of the Sith',
                'Total War: The Force Awakens',
                'Total War: The Last Jedi',
                'Total War: The Rise of Skywalker',
                'Total War: The Rise of the Machines',
                'Total War: The Matrix',
                'Total War: The Matrix Reloaded',
                'Total War: The Matrix Revolutions',
                'Total War: The Matrix Resurrections',
                'Total War: The Terminator',
                'Total War: Terminator 2: Judgment Day',
                'Total War: Terminator 3: Rise of the Machines',
                'Total War: Terminator Salvation',
                'Total War: Terminator Genisys',
                'Total War: Terminator Dark Fate',
                'Total War: Bananas',
                'Total War: Apples',
                'Total War: Oranges',
                'Total War: Pears',
                'Total War: Grapes',
                'Total War: Watermelons',
                'Total War: Pineapples',
                'Total War: Lanzones',
                'Total War: Durians',
                'Total War: Mangosteens',
                'Total War: Rambutans',
                'Total War: Lychees',
                'Total War: Longans',
            ]),
            'description' => $this->faker->paragraph,
            'release_date' => $this->faker->date,
        ];
    }
}
