<?php

namespace Database\Factories;

use App\Models\Review;
use Illuminate\Database\Eloquent\Factories\Factory;

class ReviewFactory extends Factory
{
    protected $model = Review::class;

    public function definition()
    {
        return [
            'rating' => $this->faker->randomElement([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]),
            'comment' => $this->faker->randomElement([
                'Amazing game with stunning graphics and gameplay.',
                'A decent game but could use some improvements.',
                'Not worth the hype, very disappointing.',
                'An absolute masterpiece, highly recommend!',
                'Good game but has some bugs.',
                'Enjoyable but gets repetitive after a while.',
                'Great story and characters, loved it!',
                'Mediocre game, nothing special.',
                'Fantastic multiplayer experience!',
                'Terrible game, waste of money.',
                'One of the best games I have ever played.',
                'The graphics are amazing, but the gameplay is lacking.',
                'A solid game with a few minor issues.',
                'I had a lot of fun playing this game.',
                'The story is engaging and the characters are well-developed.',
                'The game is too short for the price.',
                'I love the multiplayer mode, it\'s very addictive.',
                'The controls are clunky and hard to use.',
                'The game is very challenging, but rewarding.',
                'I would not recommend this game to anyone.',
                'The game has a lot of potential, but it needs more polish.',
                'The soundtrack is amazing and fits the game perfectly.',
                'The game is very buggy and crashes often.',
                'I enjoyed the game, but it\'s not for everyone.',
                'The game is very repetitive and gets boring quickly.',
                'The game has a lot of content and replay value.',
                'The game is too easy and lacks challenge.',
                'The game is very immersive and atmospheric.',
                'The game is very innovative and unique.',
                'The game is very frustrating and unfair.',
                'The game is very well-made and polished.',
                'The game is very addictive and hard to put down.',
                'The game is very relaxing and enjoyable.',
                'The game is very educational and informative.',
                'The game is very creative and imaginative.',
                'The game is very nostalgic and brings back memories.',
                'The game is very realistic and accurate.',
                'The game is very funny and humorous.',
                'The game is very scary and intense.',
                'The game is very emotional and touching.',
                'The game is very fast-paced and exciting.',
                'The game is very slow-paced and boring.',
                'The game is very strategic and requires planning.',
                'The game is very simple and easy to learn.',
                'The game is very complex and difficult to master.',
                'The game is very rewarding and satisfying.',
                'The game is very disappointing and underwhelming.',
                'The game is very beautiful and visually stunning.',
                'The game is very ugly and poorly designed.',
                'The game is very fun and entertaining.',
                'The game is very boring and tedious.',
                'The game is very challenging and requires skill.',
                'The game is very easy and requires no skill.',
                'The game is very innovative and original.',
                'The game is very derivative and unoriginal.',
                'The game is very immersive and engaging.',
                'The game is very shallow and uninteresting.',
                'The game is very polished and well-made.',
                'The game is very buggy and poorly made.',
                'The game is very addictive and hard to stop playing.',
                'The game is very relaxing and calming.',
                'The game is very stressful and frustrating.',
                'The game is very educational and informative.',
                'The game is very mindless and pointless.',
                'The game is very creative and imaginative.',
                'The game is very bland and uninspired.',
                'The game is very nostalgic and brings back memories.',
                'The game is very forgettable and unmemorable.',
                'The game is very realistic and accurate.',
                'The game is very unrealistic and inaccurate.',
                'The game is very funny and humorous.',
                'The game is very serious and dramatic.',
                'The game is very scary and intense.',
                'The game is very light-hearted and fun.',
                'The game is very emotional and touching.',
                'The game is very cold and unfeeling.',
                'The game is very fast-paced and exciting.',
                'The game is very slow-paced and boring.',
                'The game is very strategic and requires planning.',
                'The game is very simple and easy to learn.',
                'The game is very complex and difficult to master.',
                'The game is very rewarding and satisfying.',
                'The game is very disappointing and underwhelming.',
                'The game is very beautiful and visually stunning.',
                'The game is very ugly and poorly designed.',
                'The game is very fun and entertaining.',
                'The game is very boring and tedious.',
                'The game is very challenging and requires skill.',
                'The game is very easy and requires no skill.',
                'The game is very innovative and original.',
                'The game is very derivative and unoriginal.',
                'The game is very immersive and engaging.',
                'The game is very shallow and uninteresting.',
                'The game is very polished and well-made.',
                'The game is very buggy and poorly made.',
                'The game is very addictive and hard to stop playing.',
                'The game is very relaxing and calming.',
                'The game is very stressful and frustrating.',
                'The game is very educational and informative.',
                'The game is very mindless and pointless.',
                'The game is very creative and imaginative.',
                'The game is very bland and uninspired.',
                'The game is very nostalgic and brings back memories.',
                'The game is very forgettable and unmemorable.',
                'The game is very realistic and accurate.',
                'The game is very unrealistic and inaccurate.',
                'The game is very funny and humorous.',
                'The game is very serious and dramatic.',
                'The game is very scary and intense.',
                'The game is very light-hearted and fun.',
                'The game is very emotional and touching.',
                'The game is very cold and unfeeling.',
                'The game is very fast-paced and exciting.',
                'The game is very slow-paced and boring.',
                'The game is very strategic and requires planning.',
                'The game is very simple and easy to learn.',
                'The game is very complex and difficult to master.',
                'The game is very rewarding and satisfying.',
                'The game is very disappointing and underwhelming.',
                'The game is very beautiful and visually stunning.',
                'The game is very ugly and poorly designed.',
                'The game is very fun and entertaining.',
                'The game is very boring and tedious.',
                'The game is very challenging and requires skill.',
                'The game is very easy and requires no skill.',
                'The game is very innovative and original.',
                'The game is very derivative and unoriginal.',
                'The game is very immersive and engaging.',
                'The game is very shallow and uninteresting.',
                'The game is very polished and well-made.',
                'The game is very buggy and poorly made.',
                'The game is very addictive and hard to stop playing.',
                'The game is very relaxing and calming.',
                'The game is very stressful and frustrating.',
                'The game is very educational and informative.',
                'The game is very mindless and pointless.',
                'The game is very creative and imaginative.',
                'The game is very bland and uninspired.',
                'The game is very nostalgic and brings back memories.',
                'The game is very forgettable and unmemorable.',
                'The game is very realistic and accurate.',
                'The game is very unrealistic and inaccurate.',
                'The game is very funny and humorous.',
                'The game is very serious and dramatic.',
                'The game is very scary and intense.',
                'The game is very light-hearted and fun.',
                'The game is very emotional and touching.',
                'The game is very cold and unfeeling.',
                'The game is very fast-paced and exciting.',
                'The game is very slow-paced and boring.',
                'The game is very strategic and requires planning.',
                'The game is very simple and easy to learn.',
                'The game is very complex and difficult to master.',
                'The game is very rewarding and satisfying.',
                'The game is very disappointing and underwhelming.',
                'The game is very beautiful and visually stunning.',
                'The game is very ugly and poorly designed.',
                'The game is very fun and entertaining.',
                'The game is very boring and tedious.',
                'The game is very challenging and requires skill.',
                'The game is very easy and requires no skill.',
                'The game is very innovative and original.',
                'The game is very derivative and unoriginal.',
                'The game is very immersive and engaging.',
                'The game is very shallow and uninteresting.',
                'The game is very polished and well-made.',
                'The game is very buggy and poorly made.',
                'The game is very addictive and hard to stop playing.',
                'The game is very relaxing and calming.',
                'The game is very stressful and frustrating.',
                'The game is very educational and informative.',
                'The game is very mindless and pointless.',
                'The game is very creative and imaginative.',
                'The game is very bland and uninspired.',
                'The game is very nostalgic and brings back memories.',
                'The game is very forgettable and unmemorable.',
                'The game is very realistic and accurate.',
                'The game is very unrealistic and inaccurate.',
                'The game is very funny and humorous.',
                'The game is very serious and dramatic.',
                'The game is very scary and intense.',
                'The game is very light-hearted and fun.',
                'The game is very emotional and touching.',
                'The game is very cold and unfeeling.',
                'The game is very fast-paced and exciting.',
                'The game is very slow-paced and boring.',
                'The game is very strategic and requires planning.',
                'The game is very simple and easy to learn.',
                'The game is very complex and difficult to master.',
                'The game is very rewarding and satisfying.',
                'The game is very disappointing and underwhelming.',
                'The game is very beautiful and visually stunning.',
                'The game is very ugly and poorly designed.',
                'The game is very fun and entertaining.',
                'The game is very boring and tedious.',
                'The game is very challenging and requires skill.',
                'The game is very easy and requires no skill.',
                'The game is very innovative and original.',
                'The game is very derivative and unoriginal.',
                'The game is very immersive and engaging.',
                'The game is very shallow and uninteresting.',
                'The game is very polished and well-made.',
                'The game is very buggy and poorly made.',
                'The game is very addictive and hard to stop playing.',
                'The game is very relaxing and calming.',
                'The game is very stressful and frustrating.',
                'The game is very educational and informative.',
                'The game is very mindless and pointless.',
                'The game is very creative and imaginative.',
                'The game is very bland and uninspired.',
                'The game is very nostalgic and brings back memories.',
                'The game is very forgettable and unmemorable.',
                'The game is very realistic and accurate.',
                'The game is very unrealistic and inaccurate.',
                'The game is very funny and humorous.',
                'The game is very serious and dramatic.',
                'The game is very scary and intense.',
                'The game is very light-hearted and fun.',
                'The game is very emotional and touching.',
                'The game is very cold and unfeeling.',
                'The game is very fast-paced and exciting.',
                'The game is very slow-paced and boring.',
                'The game is very strategic and requires planning.',
                'The game is very simple and easy to learn.',
                'The game is very complex and difficult to master.',
                'The game is very rewarding and satisfying.',
                'The game is very disappointing and underwhelming.',
                'The game is very beautiful and visually stunning.',
                'The game is very ugly and poorly designed.',
                'The game is very fun and entertaining.',
                'The game is very boring and tedious.',
                'The game is very challenging and requires skill.',
                'The game is very easy and requires no skill.',
                'The game is very innovative and original.',
                'The game is very derivative and unoriginal.',
                'The game is very immersive and engaging.',
                'The game is very shallow and uninteresting.',
                'The game is very polished and well-made.',
                'The game is very buggy and poorly made.',
                'The game is very addictive and hard to stop playing.',
                'The game is very relaxing and calming.',
                'The game is very stressful and frustrating.',
                'The game is very educational and informative.',
                'The game is very mindless and pointless.',
                'The game is very creative and imaginative.',
                'The game is very bland and uninspired.',
                'The game is very nostalgic and brings back memories.',
                'The game is very forgettable and unmemorable.',
                'The game is very realistic and accurate.',
                'The game is very unrealistic and inaccurate.',
                'The game is very funny and humorous.',
                'The game is very serious and dramatic.',
                'The game is very scary and intense.',
                'The game is very light-hearted and fun.',
                'The game is very emotional and touching.',
                'The game is very cold and unfeeling.',
                'The game is very fast-paced and exciting.',
                'The game is very slow-paced and boring.',
                'The game is very strategic and requires planning.',
                'The game is very simple and easy to learn.',
                'The game is very complex and difficult to master.',
                'The game is very rewarding and satisfying.',
                'The game is very disappointing and underwhelming.',
                'The game is very beautiful and visually stunning.',
                'The game is very ugly and poorly designed.',
                'The game is very fun and entertaining.',
                'The game is very boring and tedious.',
                'The game is very challenging and requires skill.',
                'The game is very easy and requires no skill.',
                'The game is very innovative and original.',
                'The game is very derivative and unoriginal.',
                'The game is very immersive and engaging.',
                'The game is very shallow and uninteresting.',
                'The game is very polished and well-made.',
                'The game is very buggy and poorly made.',
                'The game is very addictive and hard to stop playing.',
                'The game is very relaxing and calming.',
                'The game is very stressful and frustrating.',
                'The game is very educational and informative.',
                'The game is very mindless and pointless.',
                'The game is very creative and imaginative.',
                'The game is very bland and uninspired.',
                'The game is very nostalgic and brings back memories.',
                'The game is very forgettable and unmemorable.',
                'The game is very realistic and accurate.',
                'The game is very unrealistic and inaccurate.',
                'The game is very funny and humorous.',
                'The game is very serious and dramatic.',
                'The game is very scary and intense.',
                'The game is very light-hearted and fun.',
                'The game is very emotional and touching.',
                'The game is very cold and unfeeling.',
                'The game is very fast-paced and exciting.',
                'The game is very slow-paced and boring.',
                'The game is very strategic and requires planning.',
                'The game is very simple and easy to learn.',
                'The game is very complex and difficult to master.',
                'The game is very rewarding and satisfying.',
                'The game is very disappointing and underwhelming.',
                'The game is very beautiful and visually stunning.',
                'The game is very ugly and poorly designed.',
                'The game is very fun and entertaining.',
                'The game is very boring and tedious.',
                'The game is very challenging and requires skill.',
                'The game is very easy and requires no skill.',
                'The game is very innovative and original.',
                'The game is very derivative and unoriginal.',
                'The game is very immersive and engaging.',
                'The game is very shallow and uninteresting.',
                'The game is very polished and well-made.',
                'The game is very buggy and poorly made.',
                'The game is very addictive and hard to stop playing.',
                'The game is very relaxing and calming.',
                'The game is very stressful and frustrating.',
                'The game is very educational and informative.',
                'The game is very mindless and pointless.',
                'The game is very creative and imaginative.',
                'The game is very bland and uninspired.',
                'The game is very nostalgic and brings back memories.',
                'The game is very forgettable and unmemorable.',
                'The game is very realistic and accurate.',
                'The game is very unrealistic and inaccurate.',
                'The game is very funny and humorous.',
                'The game is very serious and dramatic.',
                'The game is very scary and intense.',
                'The game is very light-hearted and fun.',
                'The game is very emotional and touching.',
                'The game is very cold and unfeeling.',
                'The game is very fast-paced and exciting.',
                'The game is very slow-paced and boring.',
                'The game is very strategic and requires planning.',
                'The game is very simple and easy to learn.',
                'The game is very complex and difficult to master.',
                'The game is very rewarding and satisfying.',
                'The game is very disappointing and underwhelming.',
                'The game is very beautiful and visually stunning.',
                'The game is very ugly and poorly designed.',
                'The game is very fun and entertaining.',
                'The game is very boring and tedious.',
                'The game is very challenging and requires skill.',
                'The game is very easy and requires no skill.',
                'The game is very innovative and original.',
                'The game is very derivative and unoriginal.',
                'The game is very immersive and engaging.',
                'The game is very shallow and uninteresting.',
                'The game is very polished and well-made.',
                'The game is very buggy and poorly made.',
                'The game is very addictive and hard to stop playing.',
                'The game is very relaxing and calming.',
                'The game is very stressful and frustrating.',
                'The game is very educational and informative.',
                'The game is very mindless and pointless.',
                'The game is very creative and imaginative.',
                'The game is very bland and uninspired.',
                'The game is very nostalgic and brings back memories.',
                'The game is very forgettable and unmemorable.',
                'The game is very realistic and accurate.',
                'The game is very unrealistic and inaccurate.',
                'The game is very funny and humorous.',
                'The game is very serious and dramatic.',
                'The game is very scary and intense.',
                'The game is very light-hearted and fun.',
                'The game is very emotional and touching.',
                'The game is very cold and unfeeling.',
                'The game is very fast-paced and exciting.',
                'The game is very slow-paced and boring.',
                'The game is very strategic and requires planning.',
                'The game is very simple and easy to learn.',
                'The game is very complex and difficult to master.',
                'The game is very rewarding and satisfying.',
                'The game is very disappointing and underwhelming.',
                'The game is very beautiful and visually stunning.',
                'The game is very ugly and poorly designed.',
                'The game is very fun and entertaining.',
                'The game is very boring and tedious.',
                'The game is very challenging and requires skill.',
                'The game is very easy and requires no skill.',
                'The game is very innovative and original.',
                'The game is very derivative and unoriginal.',
                'The game is very immersive and engaging.',
                'The game is very shallow and uninteresting.',
                'The game is very polished and well-made.',
                'The game is very buggy and poorly made.',
                'The game is very addictive and hard to stop playing.',
                'The game is very relaxing and calming.',
                'The game is very stressful and frustrating.',
                'The game is very educational and informative.',
                'The game is very mindless and pointless.',
                'The game is very creative and imaginative.',
                'The game is very bland and uninspired.',
                'The game is very nostalgic and brings back memories.',
                'The game is very forgettable and unmemorable.',
                'The game is very realistic and accurate.',
                'The game is very unrealistic and inaccurate.',
                'The game is very funny and humorous.',
                'The game is very serious and dramatic.',
                'The game is very scary and intense.',
                'The game is very light-hearted and fun.',
                'The game is very emotional and touching.',
                'The game is very cold and unfeeling.',
                'The game is very fast-paced and exciting.',
                'The game is very slow-paced and boring.',
                'The game is very strategic and requires planning.',
                'The game is very simple and easy to learn.',
                'The game is very complex and difficult to master.',
                'The game is very rewarding and satisfying.',
                'The game is very disappointing and underwhelming.',
                'The game is very beautiful and visually stunning.',
                'The game is very ugly and poorly designed.',
                'The game is very fun and entertaining.',
                'The game is very boring and tedious.',
                'The game is very challenging and requires skill.',
                'The game is very easy and requires no skill.',
                'The game is very innovative and original.',
                'The game is very derivative and unoriginal.',
                'The game is very immersive and engaging.',
                'The game is very shallow and uninteresting.',
                'The game is very polished and well-made.',
                'The game is very buggy and poorly made.',
                'The game is very addictive and hard to stop playing.',
                'The game is very relaxing and calming.',
                'The game is very stressful and frustrating.',
                'The game is very educational and informative.',
                'The game is very mindless and pointless.',
                'The game is very creative and imaginative.',
                'The game is very bland and uninspired.',
                'The game is very nostalgic and brings back memories.',
                'The game is very forgettable and unmemorable.',
                'The game is very realistic and accurate.',
                'The game is very unrealistic and inaccurate.',
                'The game is very funny and humorous.',
                'The game is very serious and dramatic.',
                'The game is very scary and intense.',
                'The game is very light-hearted and fun.',
                'The game is very emotional and touching.',
                'The game is very cold and unfeeling.',
                'The game is very fast-paced and exciting.',
                'The game is very slow-paced and boring.',
                'The game is very strategic and requires planning.',
                'The game is very simple and easy to learn.',
                'The game is very complex and difficult to master.',
                'The game is very rewarding and satisfying.',
                'The game is very disappointing and underwhelming.',
                'The game is very beautiful and visually stunning.',
                'The game is very ugly and poorly designed.',
                'The game is very fun and entertaining.',
                'The game is very boring and tedious.',
                'The game is very challenging and requires skill.',
                'The game is very easy and requires no skill.',
                'The game is very innovative and original.',
                'The game is very derivative and unoriginal.',
                'The game is very immersive and engaging.',
                'The game is very shallow and uninteresting.',
                'The game is very polished and well-made.',
                'The game is very buggy and poorly made.',
                'The game is very addictive and hard to stop playing.',
                'The game is very relaxing and calming.',
                'The game is very stressful and frustrating.',
                'The game is very educational and informative.',
                'The game is very mindless and pointless.',
                'The game is very creative and imaginative.',
                'The game is very bland and uninspired.',
                'The game is very nostalgic and brings back memories.',
                'The game is very forgettable and unmemorable.',
                'The game is very realistic and accurate.',
                'The game is very unrealistic and inaccurate.',
                'The game is very funny and humorous.',
                'The game is very serious and dramatic.',
                'The game is very scary and intense.',
                'The game is very light-hearted and fun.',
                'The game is very emotional and touching.',
                'The game is very cold and unfeeling.',
                'The game is very fast-paced and exciting.',
                'The game is very slow-paced and boring.',
                'The game is very strategic and requires planning.',
                'The game is very simple and easy to learn.',
                'The game is very complex and difficult to master.',
                'The game is very rewarding and satisfying.',
                'The game is very disappointing and underwhelming.',
                'The game is very beautiful and visually stunning.',
                'The game is very ugly and poorly designed.',
                'The game is very fun and entertaining.',
                'The game is very boring and tedious.',
                'The game is very challenging and requires skill.',
                'The game is very easy and requires no skill.',
                'The game is very innovative and original.',
                'The game is very derivative and unoriginal.',
                'The game is very immersive and engaging.',
                'The game is very shallow and uninteresting.',
                'The game is very polished and well-made.',
                'The game is very buggy and poorly made.',
                'The game is very addictive and hard to stop playing.',
                'The game is very relaxing and calming.',
                'The game is very stressful and frustrating.',
                'The game is very educational and informative.',
                'The game is very mindless and pointless.',
                'The game is very creative and imaginative.',
                'The game is very bland and uninspired.',
                'The game is very nostalgic and brings back memories.',
                'The game is very forgettable and unmemorable.',
                'The game is very realistic and accurate.',
                'The game is very unrealistic and inaccurate.',
                'The game is very funny and humorous.',
                'The game is very serious and dramatic.',
                'The game is very scary and intense.',
                'The game is very light-hearted and fun.',
                'The game is very emotional and touching.',
                'The game is very cold and unfeeling.',
                'The game is very fast-paced and exciting.',
                'The game is very slow-paced and boring.',
                'The game is very strategic and requires planning.',
                'The game is very simple and easy to learn.',
                'The game is very complex and difficult to master.',
                'The game is very rewarding and satisfying.',
                'The game is very disappointing and underwhelming.',
                'The game is very beautiful and visually stunning.',
                'The game is very ugly and poorly designed.',
                'The game is very fun and entertaining.',
                'The game is very boring and tedious.',
                'The game is very challenging and requires skill.',
                'The game is very easy and requires no skill.',
                'The game is very innovative and original.',
                'The game is very derivative and unoriginal.',
                'The game is very immersive and engaging.',
                'The game is very shallow and uninteresting.',
                'The game is very polished and well-made.',
                'The game is very buggy and poorly made.',
                'The game is very addictive and hard to stop playing.',
                'The game is very relaxing and calming.',
                'The game is very stressful and frustrating.',
                'The game is very educational and informative.',
                'The game is very mindless and pointless.',
                'The game is very creative and imaginative.',
                'The game is very bland and uninspired.',
                'The game is very nostalgic and brings back memories.',
                'The game is very forgettable and unmemorable.',
                'The game is very realistic and accurate.',
                'The game is very unrealistic and inaccurate.',
                'The game is very funny and humorous.',
                'The game is very serious and dramatic.',
                'The game is very scary and intense.',
                'The game is very light-hearted and fun.',
                'The game is very emotional and touching.',
                'The game is very cold and unfeeling.',
                'The game is very fast-paced and exciting.',
                'The game is very slow-paced and boring.',
                'The game is very strategic and requires planning.',
                'The game is very simple and easy to learn.',
                'The game is very complex and difficult to master.',
                'The game is very rewarding and satisfying.',
                'The game is very disappointing and underwhelming.',
                'The game is very beautiful and visually stunning.',
                'The game is very ugly and poorly designed.',
                'The game is very fun and entertaining.',
                'The game is very boring and tedious.',
                'The game is very challenging and requires skill.',
                'The game is very easy and requires no skill.',
                'The game is very innovative and original.',
                'The game is very derivative and unoriginal.',
                'The game is very immersive and engaging.',
                'The game is very shallow and uninteresting.',
                'The game is very polished and well-made.',
                'The game is very buggy and poorly made.',
                'The game is very addictive and hard to stop playing.',
                'The game is very relaxing and calming.',
                'The game is very stressful and frustrating.',
                'The game is very educational and informative.',
                'The game is very mindless and pointless.',
                'The game is very creative and imaginative.',
                'The game is very bland and uninspired.',
                'The game is very nostalgic and brings back memories.',
                'The game is very forgettable and unmemorable.',
                'The game is very realistic and accurate.',
                'The game is very unrealistic and inaccurate.',
                'The game is very funny and humorous.',
                'The game is very serious and dramatic.',
                'The game is very scary and intense.',
                'The game is very light-hearted and fun.',
                'The game is very emotional and touching.',
                'The game is very cold and unfeeling.',
                'The game is very fast-paced and exciting.',
                'The game is very slow-paced and boring.',
                'The game is very strategic and requires planning.',
                'The game is very simple and easy to learn.',
                'The game is very complex and difficult to master.',
                'The game is very rewarding and satisfying.',
                'The game is very disappointing and underwhelming.',
                'The game is very beautiful and visually stunning.',
                'The game is very ugly and poorly designed.',
                'The game is very fun and entertaining.',
                'The game is very boring and tedious.',
                'The game is very challenging and requires skill.',
                'The game is very easy and requires no skill.',
                'The game is very innovative and original.',
                'The game is very derivative and unoriginal.',
                'The game is very immersive and engaging.',
                'The game is very shallow and uninteresting.',
                'The game is very polished and well-made.',
                'The game is very buggy and poorly made.',
                'The game is very addictive and hard to stop playing.',
                'The game is very relaxing and calming.',
                'The game is very stressful and frustrating.',
                'The game is very educational and informative.',
                'The game is very mindless and pointless.',
                'The game is very creative and imaginative.',
                'The game is very bland and uninspired.',
                'The game is very nostalgic and brings back memories.',
                'The game is very forgettable and unmemorable.',
                'The game is very realistic and accurate.',
                'The game is very unrealistic and inaccurate.',
                'The game is very funny and humorous.',
                'The game is very serious and dramatic.',
                'The game is very scary and intense.',
                'The game is very light-hearted and fun.',
                'The game is very emotional and touching.',
                'The game is very cold and unfeeling.',
                'The game is very fast-paced and exciting.',
                'The game is very slow-paced and boring.',
                'The game is very strategic and requires planning.',
                'The game is very simple and easy to learn.',
                'The game is very complex and difficult to master.',
                'The game is very rewarding and satisfying.',
                'The game is very disappointing and underwhelming.',
                'The game is very beautiful and visually stunning.',
                'The game is very ugly and poorly designed.',
                'The game is very fun and entertaining.',
                'The game is very boring and tedious.',
                'The game is very challenging and requires skill.',
                'The game is very easy and requires no skill.',
                'The game is very innovative and original.',
                'The game is very derivative and unoriginal.',
                'The game is very immersive and engaging.',
                'The game is very shallow and uninteresting.',
                'The game is very polished and well-made.',
                'The game is very buggy and poorly made.',
                'The game is very addictive and hard to stop playing.',
                'The game is very relaxing and calming.',
                'The game is very stressful and frustrating.',
                'The game is very educational and informative.',
                'The game is very mindless and pointless.',
                'The game is very creative and imaginative.',
                'The game is very bland and uninspired.',
                'The game is very nostalgic and brings back memories.',
                'The game is very forgettable and unmemorable.',
                'The game is very realistic and accurate.',
                'The game is very unrealistic and inaccurate.',
                'The game is very funny and humorous.',
                'The game is very serious and dramatic.',
                'The game is very scary and intense.',
                'The game is very light-hearted and fun.',
                'The game is very emotional and touching.',
                'The game is very cold and unfeeling.',
                'The game is very fast-paced and exciting.',
                'The game is very slow-paced and boring.',
                'The game is very strategic and requires planning.',
                'The game is very simple and easy to learn.',
                'The game is very complex and difficult to master.',
                'The game is very rewarding and satisfying.',
                'The game is very disappointing and underwhelming.',
                'The game is very beautiful and visually stunning.',
                'The game is very ugly and poorly designed.',
                'The game is very fun and entertaining.',
                'The game is very boring and tedious.',
                'The game is very challenging and requires skill.',
                'The game is very easy and requires no skill.',
                'The game is very innovative and original.',
                'The game is very derivative and unoriginal.',
                'The game is very immersive and engaging.',
                'The game is very shallow and uninteresting.',
                'The game is very polished and well-made.',
                'The game is very buggy and poorly made.',
                'The game is very addictive and hard to stop playing.',
                'The game is very relaxing and calming.',
                'The game is very stressful and frustrating.',
                'The game is very educational and informative.',
                'The game is very mindless and pointless.',
                'The game is very creative and imaginative.',
                'The game is very bland and uninspired.',
                'The game is very nostalgic and brings back memories.',
                'The game is very forgettable and unmemorable.',
                'The game is very realistic and accurate.',
                'The game is very unrealistic and inaccurate.',
                'The game is very funny and humorous.',
                'The game is very serious and dramatic.',
                'The game is very scary and intense.',
                'The game is very light-hearted and fun.',
                'The game is very emotional and touching.',
                'The game is very cold and unfeeling.',
                'The game is very fast-paced and exciting.',
                'The game is very slow-paced and boring.',
                'The game is very strategic and requires planning.',
                'The game is very simple and easy to learn.',
                'The game is very complex and difficult to master.',
                'The game is very rewarding and satisfying.',
                'The game is very disappointing and underwhelming.',
                'The game is very beautiful and visually stunning.',
                'The game is very ugly and poorly designed.',
                'The game is very fun and entertaining.',
                'The game is very boring and tedious.',
                'The game is very challenging and requires skill.',
                'The game is very easy and requires no skill.',
                'The game is very innovative and original.',
                'The game is very derivative and unoriginal.',
                'The game is very immersive and engaging.',
                'The game is very shallow and uninteresting.',
                'The game is very polished and well-made.',
                'The game is very buggy and poorly made.',
                'The game is very addictive and hard to stop playing.',
                'The game is very relaxing and calming.',
                'The game is very stressful and frustrating.',
                'The game is very educational and informative.',
                'The game is very mindless and pointless.',
                'The game is very creative and imaginative.',
                'The game is very bland and uninspired.',
                'The game is very nostalgic and brings back memories.',
                'The game is very forgettable and unmemorable.',
                'The game is very realistic and accurate.',
                'The game is very unrealistic and inaccurate.',
                'The game is very funny and humorous.',
                'The game is very serious and dramatic.',
                'The game is very scary and intense.',
                'The game is very light-hearted and fun.',
                'The game is very emotional and touching.',
                'The game is very cold and unfeeling.',
                'The game is very fast-paced and exciting.',
                'The game is very slow-paced and boring.',
                'The game is very strategic and requires planning.',
                'The game is very simple and easy to learn.',
                'The game is very complex and difficult to master.',
                'The game is very rewarding and satisfying.',
                'The game is very disappointing and underwhelming.',
                'The game is very beautiful and visually stunning.',
                'The game is very ugly and poorly designed.',
                'The game is very fun and entertaining.',
                'The game is very boring and tedious.',
                'The game is very challenging and requires skill.',
                'The game is very easy and requires no skill.',
                'The game is very innovative and original.',
                'The game is very derivative and unoriginal.',
                'The game is very immersive and engaging.',
                'The game is very shallow and uninteresting.',
                'The game is very polished and well-made.',
                'The game is very buggy and poorly made.',
                'The game is very addictive and hard to stop playing.',
                'The game is very relaxing and calming.',
                'The game is very stressful and frustrating.',
                'The game is very educational and informative.',
                'The game is very mindless and pointless.',
                'The game is very creative and imaginative.',
                'The game is very bland and uninspired.',
                'The game is very nostalgic and brings back memories.',
                'The game is very forgettable and unmemorable.',
                'The game is very realistic and accurate.',
                'The game is very unrealistic and inaccurate.',
                'The game is very funny and humorous.',
                'The game is very serious and dramatic.',
                'The game is very scary and intense.',
                'The game is very light-hearted and fun.',
                'The game is very emotional and touching.',
                'The game is very cold and unfeeling.',
                'The game is very fast-paced and exciting.',
                'The game is very slow-paced and boring.',
                'The game is very strategic and requires planning.',
                'The game is very simple and easy to learn.',
                'The game is very complex and difficult to master.',
                'The game is very rewarding and satisfying.',
                'The game is very disappointing and underwhelming.',
                'The game is very beautiful and visually stunning.',
                'The game is very ugly and poorly designed.',
                'The game is very fun and entertaining.',
                'The game is very boring and tedious.',
                'The game is very challenging and requires skill.',
                'The game is very easy and requires no skill.',
                'The game is very innovative and original.',
                'The game is very derivative and unoriginal.',
                'The game is very immersive and engaging.',
                'The game is very shallow and uninteresting.',
                'The game is very polished and well-made.',
                'The game is very buggy and poorly made.',
                'The game is very addictive and hard to stop playing.',
                'The game is very relaxing and calming.',
                'The game is very stressful and frustrating.',
                'The game is very educational and informative.',
                'The game is very mindless and pointless.',
                'The game is very creative and imaginative.',
                'The game is very bland and uninspired.',
                'The game is very nostalgic and brings back memories.',
                'The game is very forgettable and unmemorable.',
                'The game is very realistic and accurate.',
                'The game is very unrealistic and inaccurate.',
                'The game is very funny and humorous.',
                'The game is very serious and dramatic.',
                'The game is very scary and intense.',
                'The game is very light-hearted and fun.',
                'The game is very emotional and touching.',
                'The game is very cold and unfeeling.',
                'The game is very fast-paced and exciting.',
                'The game is very slow-paced and boring.',
                'The game is very strategic and requires planning.',
                'The game is very simple and easy to learn.',
                'The game is very complex and difficult to master.',
                'The game is very rewarding and satisfying.',
                'The game is very disappointing and underwhelming.',
                'The game is very beautiful and visually stunning.',
                'The game is very ugly and poorly designed.',
                'The game is very fun and entertaining.',
                'The game is very boring and tedious.',
                'The game is very challenging and requires skill.',
                'The game is very easy and requires no skill.',
                'The game is very innovative and original.',
                'The game is very derivative and unoriginal.',
                'The game is very immersive and engaging.',
                'The game is very shallow and uninteresting.',
                'The game is very polished and well-made.',
                'The game is very buggy and poorly made.',
                'The game is very addictive and hard to stop playing.',
                'The game is very relaxing and calming.',
                'The game is very stressful and frustrating.',
                'The game is very educational and informative.',
                'The game is very mindless and pointless.',
                'The game is very creative and imaginative.',
                'The game is very bland and uninspired.',
                'The game is very nostalgic and brings back memories.',
                'The game is very forgettable and unmemorable.',
                'The game is very realistic and accurate.',
                'The game is very unrealistic and inaccurate.',
                'The game is very funny and humorous.',
                'The game is very serious and dramatic.',
                'The game is very scary and intense.',
                'The game is very light-hearted and fun.',
                'The game is very emotional and touching.',
                'The game is very cold and unfeeling.',
                'The game is very fast-paced and exciting.',
                'The game is very slow-paced and boring.',
                'The game is very strategic and requires planning.',
                'The game is very simple and easy to learn.',
                'The game is very complex and difficult to master.',
                'The game is very rewarding and satisfying.',
                'The game is very disappointing and underwhelming.',
                'The game is very beautiful and visually stunning.',
                'The game is very ugly and poorly designed.',
                'The game is very fun and entertaining.',
                'The game is very boring and tedious.',
                'The game is very challenging and requires skill.',
                'The game is very easy and requires no skill.',
                'The game is very innovative and original.',
                'The game is very derivative and unoriginal.',
                'The game is very immersive and engaging.',
                'The game is very shallow and uninteresting.',
                'The game is very polished and well-made.',
                'The game is very buggy and poorly made.',
                'The game is very addictive and hard to stop playing.',
                'The game is very relaxing and calming.',
                'The game is very stressful and frustrating.',
                'The game is very educational and informative.',
                'The game is very mindless and pointless.',
                'The game is very creative and imaginative.',
                'The game is very bland and uninspired.',
                'The game is very nostalgic and brings back memories.',
                'The game is very forgettable and unmemorable.',
                'The game is very realistic and accurate.',
                'The game is very unrealistic and inaccurate.',
                'The game is very funny and humorous.',
                'The game is very serious and dramatic.',
                'The game is very scary and intense.',
                'The game is very light-hearted and fun.',
                'The game is very emotional and touching.',
                'The game is very cold and unfeeling.',
                'The game is very fast-paced and exciting.',
                'The game is very slow-paced and boring.',
                'The game is very strategic and requires planning.',
                'The game is very simple and easy to learn.',
                'The game is very complex and difficult to master.',
                'The game is very rewarding and satisfying.',
                'The game is very disappointing and underwhelming.',
                'The game is very beautiful and visually stunning.',
                'The game is very ugly and poorly designed.',
                'The game is very fun and entertaining.',
                'The game is very boring and tedious.',
                'The game is very challenging and requires skill.',
                'The game is very easy and requires no skill.',
                'The game is very innovative and original.',
                'The game is very derivative and unoriginal.',
                'The game is very immersive and engaging.',
                'The game is very shallow and uninteresting.',
                'The game is very polished and well-made.',
                'The game is very buggy and poorly made.',
                'The game is very addictive and hard to stop playing.',
                'The game is very relaxing and calming.',
                'The game is very stressful and frustrating.',
                'The game is very educational and informative.',
                'The game is very mindless and pointless.'
            ]),
            'user_id' => \App\Models\User::factory(),
            'game_id' => \App\Models\Game::factory(),
        ];
    }
}
